language: objective-c
before_script:
  - export LANG=en_US.UTF-8
before_install:
  - brew unlink xctool
  - brew update
  - brew install xctool
xcode_project: topic.xcodeproj
xcode_scheme: topic
xcode_sdk: iphonesimulator7.1
